#include<stdio.h>
int main()
{
    int n,q,r=0,s=0,fc=0,fg=0,a=0,e=0,k=0,y=0,l=0;
    scanf("%d",&n);
    q=n;
    while(n!=0)
    {
        r=n%10;
        n=n/10;
        s=s*10+r;
        fc=fc+1;
        if(fc==3)
        break;
    }
    while(q!=0)
    {
        a=q%10;
        q=q/10;
        e=e*10+a;
    }
    while(e!=0)
    {
        k=e%10;
        e=e/10;
        y=y*10+k;
        fg=fg+1;
        if(fg==3)
        break;
    }
    l=y*1000+s;
    printf("%d",l);
}